# Generated by Django 5.2.17 on 2026-08-11 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferred_language',
        ),
    ]
