# Generated by Django 5.2.17 on 2026-08-11 11:25

import apps.itr.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('ay', models.CharField(default='2026-27', max_length=7)),
                ('model_version', models.IntegerField(default=1)),
                ('data', models.JSONField(default=apps.itr.models._default_return_data)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('field_change', 'Field change'), ('validation_run', 'Validation run'), ('json_generation', 'JSON generation'), ('advisory_ack', 'Advisory acknowledgement')], max_length=20)),
                ('field_path', models.CharField(blank=True, max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='itr.taxreturn')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='TaxFiler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=125)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('father_name', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_filers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'pan'), name='unique_owner_pan')],
            },
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['owner', 'ay'], name='itr_taxretu_owner_i_3a9a15_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['pan'], name='itr_taxretu_pan_8f029c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['tax_return', 'at'], name='itr_auditlo_tax_ret_dd9418_idx'),
        ),
    ]
