# Generated by Django 5.2.17 on 2026-08-12 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxfiler',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a valid 10-digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='taxfiler',
            name='pan',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Enter a valid PAN (e.g. ABCDE1234F).')]),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='pan',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Enter a valid PAN (e.g. ABCDE1234F).')]),
        ),
    ]
