# Generated by Django 5.2.17 on 2026-08-12 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0002_alter_taxfiler_mobile_number_alter_taxfiler_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxfiler',
            name='pan',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Enter a valid PAN.')]),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='pan',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Enter a valid PAN.')]),
        ),
    ]
