# Generated by Django 5.2.17 on 2026-08-12 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0003_alter_taxfiler_pan_alter_taxreturn_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxfiler',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{4,9}$', 'Enter a valid mobile number.')]),
        ),
        migrations.AlterField(
            model_name='taxfiler',
            name='pan',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{3}P[A-Z][0-9]{4}[A-Z]$', 'Enter a valid PAN belonging to an individual.')]),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='pan',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{3}P[A-Z][0-9]{4}[A-Z]$', 'Enter a valid PAN belonging to an individual.')]),
        ),
    ]
