# Generated by Django 5.2.17 on 2026-08-11 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxFiler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=60)),
                ('middle_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=125)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('father_name', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_filers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'pan'), name='unique_owner_pan')],
            },
        ),
    ]
