# Generated by Django 5.2.17 on 2026-08-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itr', '0002_taxfiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxreturn',
            name='screen_status',
        ),
    ]
