# Generated by Django 5.2.17 on 2026-08-07 13:48

import django.db.models.deletion
import itr1.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('ay', models.CharField(default='2026-27', max_length=7)),
                ('model_version', models.IntegerField(default=1)),
                ('data', models.JSONField(default=itr1.models._default_return_data)),
                ('screen_status', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('field_change', 'Field change'), ('validation_run', 'Validation run'), ('json_generation', 'JSON generation'), ('advisory_ack', 'Advisory acknowledgement')], max_length=20)),
                ('field_path', models.CharField(blank=True, max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tax_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='itr1.taxreturn')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['owner', 'ay'], name='itr1_taxret_owner_i_41da13_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['pan'], name='itr1_taxret_pan_5a1238_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['tax_return', 'at'], name='itr1_auditl_tax_ret_c3039e_idx'),
        ),
    ]
